name: Terraform Deploy

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main
      - staging
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
           - dev
           - staging
           - prod

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    environment: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name }}
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Target Environment
        id: set_tf_env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TF_ENV=${{github.event.inputs.environment}}" >> $GITHUB_ENV
          else
            echo "TF_ENV=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi
          echo "Deployment environment: $TF_ENV"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
           terraform_version: 1.3.0

      - name: Terraform Init
        working-directory: ./environments/${{env.TF_ENV}}
        run: terraform init

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan -var-file=environments/${{ github.ref_name }}/variables.tf